#
# Projekt: Iteracni vypocty (projekt c. 2, predmet IZP)
# Autor:   Frantisek Kolacek, xkolac12@stud.fit.vutbr.cz
# Datum:   2011/11/11
# 

CC=gcc                              
CFLAGS=-std=c99 -lm -Wall -W -Wextra -pedantic -g

proj2: proj2.c
	$(CC) $(CFLAGS) proj2.c -o proj2
