# MAKEFILE
# ITY 2015/04
# Projekt 3
# Autor: Frantisek Kolacek
# Kontakt: xkolac12@stud.fit.vutbr.cz

make: proj3.tex
	latex proj3.tex
	latex proj3.tex
	dvips -sPAPERSIZE=a4 proj3.dvi
	ps2pdf -sPAPERSIZE=a4 proj3.ps
clean:
	rm proj3.dvi proj3.ps proj3.tex~ proj3.aux 2>/dev/null 
