######################################################################
# Automatically generated by qmake (2.01a) ?t 10 3 10:00:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainForm.h \
    mywidget.h
FORMS += untitled.ui
SOURCES += main.cpp MainForm.cpp \
    mywidget.cpp
